use DATABASE MY_DEV_DB;
use role ACCOUNTADMIN;

-- service user
CREATE USER IF NOT EXISTS SERVICE_TELEMETRY_USER
  COMMENT = 'Snowflake user to ingest data from aws firehose to snowflake';

-- service role
CREATE ROLE IF NOT EXISTS SERVICE_TELEMETRY_ROLE
   comment='Role used by service user SERVICE_TELEMETRY_USER';

-- warehouse
CREATE WAREHOUSE IF NOT EXISTS TELEMETRY_INGESTION_XSMALL
  WITH
  COMMENT = 'Used by service user SERVICE_TELEMETRY_USER to ingest data from aws to snowflake.'
  WAREHOUSE_SIZE = 'XSMALL'
  INITIALLY_SUSPENDED = TRUE
;
ALTER WAREHOUSE TELEMETRY_INGESTION_XSMALL SET AUTO_SUSPEND = 60;
ALTER WAREHOUSE TELEMETRY_INGESTION_XSMALL SET AUTO_RESUME = TRUE;
ALTER WAREHOUSE TELEMETRY_INGESTION_XSMALL SET MIN_CLUSTER_COUNT = 1;
ALTER WAREHOUSE TELEMETRY_INGESTION_XSMALL SET MAX_CLUSTER_COUNT = 1;
ALTER WAREHOUSE TELEMETRY_INGESTION_XSMALL SET SCALING_POLICY = ECONOMY;